### 1 - LOGIN OK - pega token
# @name login
POST https://localhost:7246/api/usuarios/login
Content-Type: application/json

{
  "email": "fernando@example.com",
  "senha": "SenhaForte123"
}

### 2 - Salva o token em variável (espera que a resposta tenha: { "token": "..." })
@token = {{login.response.body.token}}

### 3 - 401 - rota protegida SEM token (teste obrigatório)
GET https://localhost:7246/api/usuarios
Accept: application/json


### 4 - 200 - rota protegida COM token (teste obrigatório)
GET https://localhost:7246/api/usuarios
Accept: application/json
Authorization: Bearer {{token}}


### 5 - Criar usuário (PROTEGIDO) - com token
# OBS: deixei confirmarEmail IGUAL ao email pra não dar erro de validação
POST https://localhost:7246/api/usuarios
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJmZXJuYW5kb0BleGFtcGxlLmNvbSIsImFwZWxpZG8iOiJGZXJuYXMiLCJleHAiOjE3Njc4OTY3NDksImlzcyI6IlRhbW9KdW50b0dhbWVzLkFQSSIsImF1ZCI6IlRhbW9KdW50b0dhbWVzLkZyb250ZW5kIn0.6q-TkSBShvIwkJTUZ9NlhlgLFCWQ3odfPU8xmYOQvPA

{
  "nomeCompleto": "Ana Carolina",
  "apelido": "Aninha",
  "email": "ana@example.com",
  "confirmarEmail": "ana@example.com",
  "senha": "SenhaForte123",
  "confirmarSenha": "SenhaForte123"
}


### 6 - Listar usuários (COM token)
GET https://localhost:7246/api/usuarios
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJmZXJuYW5kb0BleGFtcGxlLmNvbSIsImFwZWxpZG8iOiJGZXJuYXMiLCJleHAiOjE3Njc4OTY3NDksImlzcyI6IlRhbW9KdW50b0dhbWVzLkFQSSIsImF1ZCI6IlRhbW9KdW50b0dhbWVzLkZyb250ZW5kIn0.6q-TkSBShvIwkJTUZ9NlhlgLFCWQ3odfPU8xmYOQvPA


### 7 - Atualizar usuário (PUT) (COM token)
PUT https://localhost:7246/api/usuarios/5
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nomeCompleto": "Fernando V R C Jr Atualizado",
  "apelido": "MilosGaymes",
  "email": "ferdinando@example.com"
}


### 8 - Deletar usuário (COM token)
DELETE https://localhost:7246/api/usuarios/5
Accept: application/json
Authorization: Bearer {{token}}


### 9 - Login senha errada (deve dar 401)
POST https://localhost:7246/api/usuarios/login
Content-Type: application/json

{
  "email": "ferdinando@example.com",
  "senha": "SenhaErrada999"
}